spring:
  datasource:
    url: jdbc:postgresql://ep-shiny-dew-azddlrs7-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_xCdvYiKJB32c&sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_xCdvYiKJB32c
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never