-- ems_backend/src/main/resources/db/h2/schema-h2.sql

CREATE TABLE IF NOT EXISTS roles (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(50)  NOT NULL UNIQUE,
    description VARCHAR(255),
    created_by VARCHAR(100) NOT NULL,
    created_date TIMESTAMP  NOT NULL,
    updated_by VARCHAR(100),
    updated_date TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              VARCHAR(50)  NOT NULL UNIQUE,
    first_name           VARCHAR(100) NOT NULL,
    last_name            VARCHAR(100) NOT NULL,
    email                VARCHAR(255) NOT NULL UNIQUE,
    mobile_number        VARCHAR(20)  NOT NULL UNIQUE,
    password_hash        VARCHAR(255) NOT NULL,
    profile_photo_key    VARCHAR(255),
    address              VARCHAR(1000),
    years_of_experience  INT,
    current_skill_level  VARCHAR(10)  NOT NULL,
    current_organization VARCHAR(255),
    qualification        VARCHAR(255),
    father_name          VARCHAR(255),
    enabled              BOOLEAN      NOT NULL,
    account_non_locked   BOOLEAN      NOT NULL,
    created_by           VARCHAR(100) NOT NULL,
    created_date         TIMESTAMP    NOT NULL,
    updated_by           VARCHAR(100),
    updated_date         TIMESTAMP,
    CONSTRAINT chk_users_skill_level CHECK (current_skill_level IN ('L1', 'L2', 'L3'))
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id      BIGINT NOT NULL,
    role_id      BIGINT NOT NULL,
    created_by   VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    created_date TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by   VARCHAR(100),
    updated_date TIMESTAMP,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_ref     BIGINT       NOT NULL,
    token_hash   VARCHAR(255) NOT NULL UNIQUE,
    issued_at    TIMESTAMP    NOT NULL,
    expires_at   TIMESTAMP    NOT NULL,
    revoked      BOOLEAN      NOT NULL,
    created_by   VARCHAR(100) NOT NULL,
    created_date TIMESTAMP    NOT NULL,
    updated_by   VARCHAR(100),
    updated_date TIMESTAMP,
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_ref) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_ref     BIGINT       NOT NULL,
    token_hash   VARCHAR(255) NOT NULL UNIQUE,
    expires_at   TIMESTAMP    NOT NULL,
    used         BOOLEAN      NOT NULL,
    created_by   VARCHAR(100) NOT NULL,
    created_date TIMESTAMP    NOT NULL,
    updated_by   VARCHAR(100),
    updated_date TIMESTAMP,
    CONSTRAINT fk_password_reset_tokens_user FOREIGN KEY (user_ref) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS certifications (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_ref             BIGINT      NOT NULL,
    certification_level  VARCHAR(10) NOT NULL,
    certification_status VARCHAR(20) NOT NULL,
    issue_date           DATE        NOT NULL,
    expiry_date          DATE        NOT NULL,
    created_by           VARCHAR(100) NOT NULL,
    created_date         TIMESTAMP    NOT NULL,
    updated_by           VARCHAR(100),
    updated_date         TIMESTAMP,
    CONSTRAINT fk_certifications_user FOREIGN KEY (user_ref) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT chk_certification_level  CHECK (certification_level IN ('L1', 'L2', 'L3')),
    CONSTRAINT chk_certification_status CHECK (certification_status IN ('ACTIVE', 'EXPIRED', 'REVOKED'))
);

CREATE TABLE IF NOT EXISTS certification_history (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    certification_ref BIGINT       NOT NULL,
    event_type        VARCHAR(50)  NOT NULL,
    event_description VARCHAR(2000),
    event_timestamp   TIMESTAMP    NOT NULL,
    created_by        VARCHAR(100) NOT NULL,
    created_date      TIMESTAMP    NOT NULL,
    updated_by        VARCHAR(100),
    updated_date      TIMESTAMP,
    CONSTRAINT fk_certification_history_certification FOREIGN KEY (certification_ref) REFERENCES certifications (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS exams (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_code           VARCHAR(50)    NOT NULL UNIQUE,
    exam_name           VARCHAR(255)   NOT NULL,
    certification_level VARCHAR(10)    NOT NULL,
    duration_minutes    INT            NOT NULL,
    total_marks         DECIMAL(10, 2) NOT NULL,
    passing_percentage  DECIMAL(5, 2)  NOT NULL,
    exam_status         VARCHAR(20)    NOT NULL,
    published           BOOLEAN        NOT NULL,
    scheduled_start_time TIMESTAMP,
    scheduled_end_time   TIMESTAMP,
    created_by          VARCHAR(100)   NOT NULL,
    created_date        TIMESTAMP      NOT NULL,
    updated_by          VARCHAR(100),
    updated_date        TIMESTAMP,
    CONSTRAINT chk_exam_level            CHECK (certification_level IN ('L1', 'L2', 'L3')),
    CONSTRAINT chk_exam_status           CHECK (exam_status IN ('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'PASSED', 'FAILED', 'INVALIDATED')),
    CONSTRAINT chk_exam_duration         CHECK (duration_minutes > 0),
    CONSTRAINT chk_exam_total_marks      CHECK (total_marks >= 0),
    CONSTRAINT chk_exam_passing_percentage CHECK (passing_percentage >= 0 AND passing_percentage <= 100)
);

CREATE TABLE IF NOT EXISTS certification_applications (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_ref             BIGINT      NOT NULL,
    exam_ref             BIGINT,
    certification_level  VARCHAR(10) NOT NULL,
    application_status   VARCHAR(20) NOT NULL,
    payment_status       VARCHAR(20) NOT NULL,
    applied_on           DATE        NOT NULL,
    scheduled_exam_time  TIMESTAMP,
    remarks              VARCHAR(1000),
    created_by           VARCHAR(100) NOT NULL,
    created_date         TIMESTAMP    NOT NULL,
    updated_by           VARCHAR(100),
    updated_date         TIMESTAMP,
    CONSTRAINT fk_certification_applications_user FOREIGN KEY (user_ref) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_certification_applications_exam FOREIGN KEY (exam_ref) REFERENCES exams (id) ON DELETE SET NULL,
    CONSTRAINT chk_application_level   CHECK (certification_level IN ('L1', 'L2', 'L3')),
    CONSTRAINT chk_application_status  CHECK (application_status IN ('APPLIED', 'ELIGIBLE', 'IN_PROGRESS', 'PASSED', 'FAILED', 'REJECTED', 'EXPIRED')),
    CONSTRAINT chk_application_payment_status CHECK (payment_status IN ('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED'))
);

CREATE TABLE IF NOT EXISTS questions (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_code        VARCHAR(50)    NOT NULL UNIQUE,
    certification_level  VARCHAR(10)    NOT NULL,
    question_category    VARCHAR(20)    NOT NULL,
    question_type        VARCHAR(20)    NOT NULL,
    question_text        VARCHAR(4000)  NOT NULL,
    options_json         CLOB           NOT NULL,
    correct_options_json CLOB           NOT NULL,
    severity             VARCHAR(10)    NOT NULL,
    marks                DECIMAL(10, 2) NOT NULL,
    active               BOOLEAN        NOT NULL,
    created_by           VARCHAR(100)   NOT NULL,
    created_date         TIMESTAMP      NOT NULL,
    updated_by           VARCHAR(100),
    updated_date         TIMESTAMP,
    CONSTRAINT chk_question_level    CHECK (certification_level IN ('L1', 'L2', 'L3')),
    CONSTRAINT chk_question_category CHECK (question_category IN ('Technical', 'Functional', 'Compliance', 'General')),
    CONSTRAINT chk_question_type     CHECK (question_type IN ('Single Choice', 'Multiple Choice')),
    CONSTRAINT chk_question_severity CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH'))
);

CREATE TABLE IF NOT EXISTS payments (
    id                          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id              VARCHAR(100)    NOT NULL UNIQUE,
    user_ref                    BIGINT          NOT NULL,
    exam_ref                    BIGINT          NOT NULL,
    certification_application_ref BIGINT,
    amount                      DECIMAL(12, 2)  NOT NULL,
    currency                    VARCHAR(10)     NOT NULL,
    provider                    VARCHAR(30)     NOT NULL,
    payment_status              VARCHAR(20)     NOT NULL,
    payment_date                TIMESTAMP,
    provider_reference          VARCHAR(100),
    created_by                  VARCHAR(100)    NOT NULL,
    created_date                TIMESTAMP       NOT NULL,
    updated_by                  VARCHAR(100),
    updated_date                TIMESTAMP,
    CONSTRAINT fk_payments_user        FOREIGN KEY (user_ref) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_payments_exam        FOREIGN KEY (exam_ref) REFERENCES exams (id) ON DELETE CASCADE,
    CONSTRAINT fk_payments_application FOREIGN KEY (certification_application_ref) REFERENCES certification_applications (id) ON DELETE SET NULL,
    CONSTRAINT chk_payments_status     CHECK (payment_status IN ('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED'))
);

CREATE TABLE IF NOT EXISTS exam_sessions (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_token            UUID         NOT NULL UNIQUE,
    user_ref                 BIGINT       NOT NULL,
    exam_ref                 BIGINT       NOT NULL,
    session_start_time       TIMESTAMP    NOT NULL,
    session_end_time         TIMESTAMP,
    session_status           VARCHAR(20)  NOT NULL,
    violation_count          INT          NOT NULL,
    browser_fingerprint      VARCHAR(255),
    ip_address               VARCHAR(64),
    selected_question_ids_json CLOB,
    created_by               VARCHAR(100) NOT NULL,
    created_date             TIMESTAMP    NOT NULL,
    updated_by               VARCHAR(100),
    updated_date             TIMESTAMP,
    CONSTRAINT fk_exam_sessions_user FOREIGN KEY (user_ref) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_exam_sessions_exam FOREIGN KEY (exam_ref) REFERENCES exams (id) ON DELETE CASCADE,
    CONSTRAINT chk_exam_session_status CHECK (session_status IN ('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'PASSED', 'FAILED', 'INVALIDATED'))
);

CREATE TABLE IF NOT EXISTS exam_attempts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_session_ref    BIGINT         NOT NULL,
    total_questions     INT            NOT NULL,
    attempted_questions INT            NOT NULL,
    correct_answers     INT            NOT NULL,
    wrong_answers       INT            NOT NULL,
    obtained_marks      DECIMAL(10, 2) NOT NULL,
    percentage          DECIMAL(5, 2)  NOT NULL,
    result_status       VARCHAR(10)    NOT NULL,
    submitted_at        TIMESTAMP,
    created_by          VARCHAR(100)   NOT NULL,
    created_date        TIMESTAMP      NOT NULL,
    updated_by          VARCHAR(100),
    updated_date        TIMESTAMP,
    CONSTRAINT fk_exam_attempts_session     FOREIGN KEY (exam_session_ref) REFERENCES exam_sessions (id) ON DELETE CASCADE,
    CONSTRAINT chk_exam_attempt_result_status CHECK (result_status IN ('PASS', 'FAIL'))
);

CREATE TABLE IF NOT EXISTS certificates (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    certificate_number VARCHAR(100)  NOT NULL UNIQUE,
    certification_ref  BIGINT        NOT NULL,
    exam_attempt_ref   BIGINT        NOT NULL,
    certificate_url    VARCHAR(4000),
    qr_code_url        VARCHAR(4000),
    verification_url   VARCHAR(4000) NOT NULL,
    issue_date         DATE          NOT NULL,
    expiry_date        DATE          NOT NULL,
    created_by         VARCHAR(100)  NOT NULL,
    created_date       TIMESTAMP     NOT NULL,
    updated_by         VARCHAR(100),
    updated_date       TIMESTAMP,
    CONSTRAINT fk_certificates_certification FOREIGN KEY (certification_ref) REFERENCES certifications (id) ON DELETE CASCADE,
    CONSTRAINT fk_certificates_attempt       FOREIGN KEY (exam_attempt_ref) REFERENCES exam_attempts (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS violations (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_session_ref BIGINT       NOT NULL,
    violation_type   VARCHAR(80)  NOT NULL,
    violation_level  INT          NOT NULL,
    description      VARCHAR(4000),
    detected_at      TIMESTAMP    NOT NULL,
    action_taken     VARCHAR(80),
    created_by       VARCHAR(100) NOT NULL,
    created_date     TIMESTAMP    NOT NULL,
    updated_by       VARCHAR(100),
    updated_date     TIMESTAMP,
    CONSTRAINT fk_violations_session    FOREIGN KEY (exam_session_ref) REFERENCES exam_sessions (id) ON DELETE CASCADE,
    CONSTRAINT chk_violation_level      CHECK (violation_level > 0)
);

CREATE TABLE IF NOT EXISTS video_recordings (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_session_ref           BIGINT        NOT NULL,
    file_location              VARCHAR(4000) NOT NULL,
    recording_start_time       TIMESTAMP     NOT NULL,
    recording_end_time         TIMESTAMP,
    recording_duration_seconds BIGINT,
    created_by                 VARCHAR(100)  NOT NULL,
    created_date               TIMESTAMP     NOT NULL,
    updated_by                 VARCHAR(100),
    updated_date               TIMESTAMP,
    CONSTRAINT fk_video_recordings_session FOREIGN KEY (exam_session_ref) REFERENCES exam_sessions (id) ON DELETE CASCADE
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_users_email          ON users (email);
CREATE INDEX IF NOT EXISTS idx_users_mobile_number  ON users (mobile_number);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_revoked         ON refresh_tokens (user_ref, revoked);
CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_user_used     ON password_reset_tokens (user_ref, used);
CREATE INDEX IF NOT EXISTS idx_certifications_user_level           ON certifications (user_ref, certification_level);
CREATE INDEX IF NOT EXISTS idx_certification_applications_user_level ON certification_applications (user_ref, certification_level);
CREATE INDEX IF NOT EXISTS idx_questions_level_severity            ON questions (certification_level, severity);
CREATE INDEX IF NOT EXISTS idx_exams_level_published               ON exams (certification_level, published);
CREATE INDEX IF NOT EXISTS idx_payments_application_ref            ON payments (certification_application_ref);
CREATE INDEX IF NOT EXISTS idx_certification_app_user_status_applied ON certification_applications (user_ref, application_status, applied_on);
CREATE INDEX IF NOT EXISTS idx_payments_status_date                ON payments (payment_status, payment_date);
CREATE UNIQUE INDEX IF NOT EXISTS uq_exam_attempts_session_ref     ON exam_attempts (exam_session_ref);
CREATE INDEX IF NOT EXISTS idx_exam_attempts_submitted_at          ON exam_attempts (submitted_at);
CREATE INDEX IF NOT EXISTS idx_exam_attempts_result_submitted      ON exam_attempts (result_status, submitted_at);
CREATE UNIQUE INDEX IF NOT EXISTS uq_certificates_attempt_ref      ON certificates (exam_attempt_ref);
CREATE INDEX IF NOT EXISTS idx_certificates_number                 ON certificates (certificate_number);
CREATE INDEX IF NOT EXISTS idx_certificates_issue_expiry           ON certificates (issue_date, expiry_date);
CREATE INDEX IF NOT EXISTS idx_violations_session_detected         ON violations (exam_session_ref, detected_at);
CREATE INDEX IF NOT EXISTS idx_violations_type_detected            ON violations (violation_type, detected_at);
